version: '3'

services:
  app:
    # 根据自己的系统选择x86_64还是aarch64
    image: chatglm
    # image: wenjing95/chatgpt-web-backend:aarch64
    ports:
      - 3002:3002
    environment:
      model_path: "/model"
      Device: "cpu"
      Quantize: 16
      # HOST，可选，默认值为 0.0.0.0
      HOST: 0.0.0.0
      # PORT，可选，默认值为 3002
      PORT: 3002
    volumes:
      - /home/zkw/code/gpt/chatglm-6b-int4:/model
  nginx:
    depends_on:
      - app
    image: nginx:alpine
    ports:
      - '80:80'
    expose:
      - '80'
    volumes:
      - ./nginx/html/:/etc/nginx/html/
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - app
