repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
    - id: check-yaml
    - id: trailing-whitespace
    - id: end-of-file-fixer

# - repo: https://github.com/pycqa/pylint
#   rev: v2.15.5
#   hooks:
#     - id: pylint
#       args:
#         - "--rcfile=.pylintrc"
#       exclude: tests(/\w*)*/functional/|tests/input|tests(/\w*)*data/|doc/|TFserving/ClientAPI/go/pkg/

- repo: https://github.com/google/yapf
  rev: v0.32.0
  hooks:
  - id: yapf

# - repo: https://github.com/pre-commit/mirrors-mypy
#   rev: v0.982
#   hooks:
#     - id: mypy
#       additional_dependencies: ['types-requests']
#       exclude:  tests(/\w*)*/functional/|tests/input|tests(/\w*)*data/|doc/|TFserving/ClientAPI/go/pkg/|(/\w*)*_test.py

- repo: https://github.com/pre-commit/mirrors-clang-format
  rev: 'v14.0.6'
  hooks:
  - id: clang-format
    types_or: [c++, c]

- repo: https://github.com/mwouts/jupytext
  rev: v1.14.1
  hooks:
  - id: jupytext
    args: [--sync]

- repo: https://github.com/cheshirekow/cmake-format-precommit
  rev: v0.6.10
  hooks:
  - id: cmake-format
  - id: cmake-lint
